'use strict';
const $=(s)=>document.querySelector(s),DEFAULT_LANGUAGE='en';
const I18N={
 en:{bloxd:'Bloxd',notDetected:'not detected',mode:'Mode',passive:'Passive',verifyKicker:'HUB VERIFY',waiting:'Waiting for Bloxd',waitingText:'Open the HUB / tournament lobby in Bloxd. The extension then works completely passively.',active:'PASSIVE BRIDGE ACTIVE',activeText:'Verification data is processed automatically in the background. HUB Verify never writes into Bloxd chat and never takes keyboard focus.',syncKicker:'BACKGROUND SYNC',noneProcessed:'No new verification data processed yet.',latest:a=>`Latest background processing ${a}.`,hubKicker:'HUB CONNECTION',connected:'CONNECTED',connectedText:'The latest new registration was sent to the HUB successfully.',connectionError:'CONNECTION ERROR',retryText:'The bridge will retry on a later replay.',ready:'READY',offline:'OFFLINE',idleText:'Already verified players are skipped automatically.',openHub:'OPEN HUB',openBloxd:'OPEN BLOXD',clear:'Reset diagnostic counters',privacy:"The extension never displays other players' names or registration codes. Your own successful verification appears directly in game.",sec:n=>`${n}s ago`,min:n=>`${n} min ago`},
 de:{bloxd:'Bloxd',notDetected:'nicht erkannt',mode:'Modus',passive:'Passiv',verifyKicker:'HUB VERIFY',waiting:'Wartet auf Bloxd',waitingText:'Öffne die HUB-/Turnierlobby in Bloxd. Die Extension arbeitet danach vollständig passiv.',active:'PASSIVE BRIDGE AKTIV',activeText:'Verifizierungsdaten werden automatisch im Hintergrund verarbeitet. HUB Verify schreibt nichts in den Bloxd-Chat und übernimmt niemals den Eingabefokus.',syncKicker:'HINTERGRUND-SYNC',noneProcessed:'Noch keine neuen Verifizierungsdaten verarbeitet.',latest:a=>`Letzte Hintergrund-Verarbeitung ${a}.`,hubKicker:'VERBINDUNG ZUM HUB',connected:'VERBUNDEN',connectedText:'Die letzte neue Registrierung wurde erfolgreich an den HUB übertragen.',connectionError:'VERBINDUNGSFEHLER',retryText:'Die Bridge versucht es bei einem späteren Replay erneut.',ready:'BEREIT',offline:'OFFLINE',idleText:'Bereits verifizierte Spieler werden automatisch übersprungen.',openHub:'HUB ÖFFNEN',openBloxd:'BLOXD ÖFFNEN',clear:'Diagnose-Zähler zurücksetzen',privacy:'Die Extension zeigt keine Namen oder Registrierungscodes anderer Spieler an. Eigene erfolgreiche Verifizierungen erscheinen direkt im Spiel.',sec:n=>`vor ${n}s`,min:n=>`vor ${n}min`},
 fr:{bloxd:'Bloxd',notDetected:'non détecté',mode:'Mode',passive:'Passif',verifyKicker:'HUB VERIFY',waiting:'En attente de Bloxd',waitingText:'Ouvre le lobby HUB / tournoi dans Bloxd. L’extension fonctionne ensuite entièrement en arrière-plan.',active:'BRIDGE PASSIF ACTIF',activeText:'Les données de vérification sont traitées automatiquement en arrière-plan. HUB Verify n’écrit jamais dans le chat Bloxd et ne prend jamais le focus clavier.',syncKicker:'SYNCHRO EN ARRIÈRE-PLAN',noneProcessed:'Aucune nouvelle donnée de vérification traitée.',latest:a=>`Dernier traitement en arrière-plan ${a}.`,hubKicker:'CONNEXION AU HUB',connected:'CONNECTÉ',connectedText:'La dernière nouvelle inscription a été transmise au HUB.',connectionError:'ERREUR DE CONNEXION',retryText:'La bridge réessaiera lors d’un prochain replay.',ready:'PRÊT',offline:'HORS LIGNE',idleText:'Les joueurs déjà vérifiés sont ignorés automatiquement.',openHub:'OUVRIR LE HUB',openBloxd:'OUVRIR BLOXD',clear:'Réinitialiser les compteurs de diagnostic',privacy:'L’extension n’affiche jamais les noms ni les codes d’inscription des autres joueurs. Ta propre vérification réussie apparaît directement en jeu.',sec:n=>`il y a ${n}s`,min:n=>`il y a ${n} min`}
};
let language=DEFAULT_LANGUAGE,lastState={},lastVersion='0.9.4';
const tr=(key,...args)=>{const v=I18N[language]?.[key]??I18N.en[key]??key;return typeof v==='function'?v(...args):v;};
function recent(ts,maxAge=120000){return Number(ts||0)>Date.now()-maxAge;}
function ago(ts){const s=Math.max(0,Math.round((Date.now()-Number(ts||0))/1000));return s<60?tr('sec',s):tr('min',Math.round(s/60));}
function render(state=lastState,version=lastVersion){lastState=state||{};lastVersion=version||'0.9.4';document.documentElement.lang=language;$('#language').value=language;$('#version').textContent=`v${lastVersion}`;$('#bloxdLabel').textContent=tr('bloxd');$('#modeLabel').textContent=tr('mode');$('#modeValue').textContent=tr('passive');$('#verifyKicker').textContent=tr('verifyKicker');$('#syncKicker').textContent=tr('syncKicker');$('#hubKicker').textContent=tr('hubKicker');$('#openHub').textContent=tr('openHub');$('#openBloxd').textContent=tr('openBloxd');$('#clear').textContent=tr('clear');$('#privacy').textContent=tr('privacy');const online=recent(state.bloxdSeenAt);$('#bloxdDot').classList.toggle('on',online);$('#bloxdStatus').textContent=online?ago(state.bloxdSeenAt):tr('notDetected');$('#relayTitle').textContent=online?tr('active'):tr('waiting');$('#relayText').textContent=online?tr('activeText'):tr('waitingText');$('#assertionCount').textContent=String(Number(state.totalAssertionsUploaded||0));const latest=Array.isArray(state.recentAssertions)&&state.recentAssertions[0];$('#latestAssertion').textContent=latest?tr('latest',ago(latest.seenAt)):tr('noneProcessed');const up=state.latestUpload;if(up?.ok){$('#uploadStatus').textContent=tr('connected');$('#uploadText').textContent=tr('connectedText');}else if(up){$('#uploadStatus').textContent=tr('connectionError');$('#uploadText').textContent=tr('retryText');}else{$('#uploadStatus').textContent=online?tr('ready'):tr('offline');$('#uploadText').textContent=tr('idleText');}}
async function loadLanguage(){const stored=await chrome.storage.local.get({hubLanguage:DEFAULT_LANGUAGE});language=['en','de','fr'].includes(stored.hubLanguage)?stored.hubLanguage:DEFAULT_LANGUAGE;}
async function refresh(){const r=await chrome.runtime.sendMessage({type:'HUB_EXTENSION_GET_STATE'});if(r?.ok)render(r.state||{},r.version);}
$('#language').addEventListener('change',async e=>{language=['en','de','fr'].includes(e.target.value)?e.target.value:DEFAULT_LANGUAGE;await chrome.storage.local.set({hubLanguage:language});render();});
$('#openHub').addEventListener('click',()=>chrome.runtime.sendMessage({type:'OPEN_HUB'}));$('#openBloxd').addEventListener('click',()=>chrome.runtime.sendMessage({type:'OPEN_BLOXD'}));$('#clear').addEventListener('click',async()=>{await chrome.runtime.sendMessage({type:'HUB_EXTENSION_CLEAR'});await refresh();});
(async()=>{await loadLanguage();await refresh();setInterval(refresh,2500);})();
