"use strict";
const $=(s)=>document.querySelector(s),DEFAULT_LANGUAGE='en';
const I18N={
 en:{bloxd:'Bloxd',notDetected:'not detected',mode:'Mode',fullRelay:'Full Relay',verifyKicker:'HUB VERIFY',waiting:'Waiting for Bloxd',waitingText:'Open the HUB / tournament lobby in Bloxd. Verification and tournament live sync then run automatically.',active:'HUB RELAY ACTIVE',activeText:'Account verification and tournament live events are processed silently in the background. HUB Verify never writes into Bloxd chat and never takes keyboard focus.',syncKicker:'ACCOUNT VERIFICATION',noneProcessed:'No new verification data processed yet.',latest:a=>`Latest verification ${a}.`,liveKicker:'TOURNAMENT LIVE SYNC',noneLive:'No tournament events relayed yet.',latestLive:(type,a)=>`Latest event ${type||'LIVE'} ${a}.`,hubKicker:'HUB CONNECTION',connected:'CONNECTED',connectedText:'The latest relay data was sent to the HUB successfully.',connectionError:'CONNECTION ERROR',retryText:'The bridge will retry when Bloxd sends the event again.',ready:'READY',offline:'OFFLINE',idleText:'The HUB relay is ready.',openHub:'OPEN HUB',openBloxd:'OPEN BLOXD',clear:'Reset diagnostic counters',privacy:'HUB Verify works silently in the background, never types into Bloxd chat and never takes keyboard focus.',sec:n=>`${n}s ago`,min:n=>`${n} min ago`},
 de:{bloxd:'Bloxd',notDetected:'nicht erkannt',mode:'Modus',fullRelay:'Vollständiges Relay',verifyKicker:'HUB VERIFY',waiting:'Wartet auf Bloxd',waitingText:'Öffne die HUB-/Turnierlobby in Bloxd. Verifizierung und Turnier-Live-Sync laufen danach automatisch.',active:'HUB RELAY AKTIV',activeText:'Account-Verifizierung und Turnier-Live-Events werden still im Hintergrund verarbeitet. HUB Verify schreibt nichts in den Bloxd-Chat und übernimmt niemals den Eingabefokus.',syncKicker:'ACCOUNT-VERIFIZIERUNG',noneProcessed:'Noch keine neuen Verifizierungsdaten verarbeitet.',latest:a=>`Letzte Verifizierung ${a}.`,liveKicker:'TURNIER LIVE-SYNC',noneLive:'Noch keine Turnier-Events übertragen.',latestLive:(type,a)=>`Letztes Event ${type||'LIVE'} ${a}.`,hubKicker:'VERBINDUNG ZUM HUB',connected:'VERBUNDEN',connectedText:'Die letzten Relay-Daten wurden erfolgreich an den HUB übertragen.',connectionError:'VERBINDUNGSFEHLER',retryText:'Die Bridge versucht es erneut, sobald Bloxd das Event erneut sendet.',ready:'BEREIT',offline:'OFFLINE',idleText:'Das HUB-Relay ist bereit.',openHub:'HUB ÖFFNEN',openBloxd:'BLOXD ÖFFNEN',clear:'Diagnose-Zähler zurücksetzen',privacy:'HUB Verify arbeitet still im Hintergrund, schreibt nichts in den Bloxd-Chat und übernimmt niemals den Eingabefokus.',sec:n=>`vor ${n}s`,min:n=>`vor ${n}min`},
 fr:{bloxd:'Bloxd',notDetected:'non détecté',mode:'Mode',fullRelay:'Relais complet',verifyKicker:'HUB VERIFY',waiting:'En attente de Bloxd',waitingText:'Ouvre le lobby HUB / tournoi dans Bloxd. La vérification et la synchro tournoi fonctionnent ensuite automatiquement.',active:'RELAIS HUB ACTIF',activeText:'La vérification des comptes et les événements du tournoi sont traités silencieusement en arrière-plan. HUB Verify n’écrit jamais dans le chat Bloxd et ne prend jamais le focus clavier.',syncKicker:'VÉRIFICATION DU COMPTE',noneProcessed:'Aucune nouvelle donnée de vérification traitée.',latest:a=>`Dernière vérification ${a}.`,liveKicker:'SYNCHRO TOURNOI EN DIRECT',noneLive:'Aucun événement de tournoi transmis.',latestLive:(type,a)=>`Dernier événement ${type||'LIVE'} ${a}.`,hubKicker:'CONNEXION AU HUB',connected:'CONNECTÉ',connectedText:'Les dernières données du relais ont été envoyées au HUB.',connectionError:'ERREUR DE CONNEXION',retryText:'Le relais réessaiera lorsque Bloxd renverra l’événement.',ready:'PRÊT',offline:'HORS LIGNE',idleText:'Le relais HUB est prêt.',openHub:'OUVRIR LE HUB',openBloxd:'OUVRIR BLOXD',clear:'Réinitialiser les compteurs de diagnostic',privacy:'HUB Verify fonctionne silencieusement en arrière-plan, n’écrit jamais dans le chat Bloxd et ne prend jamais le focus clavier.',sec:n=>`il y a ${n}s`,min:n=>`il y a ${n} min`}
};
let language=DEFAULT_LANGUAGE,lastState={},lastVersion='1.0.9';
const tr=(key,...args)=>{const v=I18N[language]?.[key]??I18N.en[key]??key;return typeof v==='function'?v(...args):v;};
function recent(ts,maxAge=120000){return Number(ts||0)>Date.now()-maxAge;}
function ago(ts){const s=Math.max(0,Math.round((Date.now()-Number(ts||0))/1000));return s<60?tr('sec',s):tr('min',Math.round(s/60));}
function render(state=lastState,version=lastVersion){lastState=state||{};lastVersion=version||'1.0.9';document.documentElement.lang=language;$('#language').value=language;$('#version').textContent=`v${lastVersion}`;$('#bloxdLabel').textContent=tr('bloxd');$('#modeLabel').textContent=tr('mode');$('#modeValue').textContent=tr('fullRelay');$('#verifyKicker').textContent=tr('verifyKicker');$('#syncKicker').textContent=tr('syncKicker');$('#liveKicker').textContent=tr('liveKicker');$('#hubKicker').textContent=tr('hubKicker');$('#openHub').textContent=tr('openHub');$('#openBloxd').textContent=tr('openBloxd');$('#clear').textContent=tr('clear');$('#privacy').textContent=tr('privacy');const online=recent(state.bloxdSeenAt);$('#bloxdDot').classList.toggle('on',online);$('#bloxdStatus').textContent=online?ago(state.bloxdSeenAt):tr('notDetected');$('#relayTitle').textContent=online?tr('active'):tr('waiting');$('#relayText').textContent=online?tr('activeText'):tr('waitingText');$('#assertionCount').textContent=String(Number(state.totalAssertionsUploaded||0));const latest=Array.isArray(state.recentAssertions)&&state.recentAssertions[0];$('#latestAssertion').textContent=latest?tr('latest',ago(latest.seenAt)):tr('noneProcessed');$('#liveCount').textContent=String(Number(state.totalLiveUploaded||0));const latestLive=Array.isArray(state.recentLive)&&state.recentLive[0];$('#latestLive').textContent=latestLive?tr('latestLive',latestLive.type,ago(latestLive.seenAt)):tr('noneLive');const up=state.latestLiveUpload||state.latestUpload;if(up?.ok){$('#uploadStatus').textContent=tr('connected');$('#uploadText').textContent=tr('connectedText');}else if(up){$('#uploadStatus').textContent=tr('connectionError');$('#uploadText').textContent=tr('retryText');}else{$('#uploadStatus').textContent=online?tr('ready'):tr('offline');$('#uploadText').textContent=tr('idleText');}}
async function loadLanguage(){const stored=await chrome.storage.local.get({hubLanguage:DEFAULT_LANGUAGE});language=['en','de','fr'].includes(stored.hubLanguage)?stored.hubLanguage:DEFAULT_LANGUAGE;}
async function refresh(){const r=await chrome.runtime.sendMessage({type:'HUB_EXTENSION_GET_STATE'});if(r?.ok)render(r.state||{},r.version);}
$('#language').addEventListener('change',async e=>{language=['en','de','fr'].includes(e.target.value)?e.target.value:DEFAULT_LANGUAGE;await chrome.storage.local.set({hubLanguage:language});render();});
$('#openHub').addEventListener('click',()=>chrome.runtime.sendMessage({type:'OPEN_HUB'}));$('#openBloxd').addEventListener('click',()=>chrome.runtime.sendMessage({type:'OPEN_BLOXD'}));$('#clear').addEventListener('click',async()=>{await chrome.runtime.sendMessage({type:'HUB_EXTENSION_CLEAR'});await refresh();});
(async()=>{await loadLanguage();await refresh();setInterval(refresh,2500);})();
