const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'source/identity-worker.js'),'utf8'),results=[];
async function test(name,fn){await fn();results.push({name,passed:true});}
const sender=(tab=1,f=0,doc='a')=>({id:'test-extension',url:'https://bloxd.io/play/test',tab:{id:tab},frameId:f,documentId:doc});
const mark=(t,a)=>`__SG_EVT__|${t}|sg-hub-identity-20260920|${Buffer.from(JSON.stringify(a)).toString('base64url')}|SIG=${'x'.repeat(43)}`;
const own=(db='AliceDb111111',at=Date.now())=>mark('REGSELF2',[db,'Alice','ABCDEFGH',at,at+28800000,'s'.repeat(43),2,'identity-notices']);
const event=(i=0)=>{const n=String(i).padStart(43,'n');return mark('REGASSERT2',[`hub-id2:AliceDb111111:${n}`,'AliceDb111111','Alice',n,Date.now()+i,Date.now(),'identity',2]);};
const a=raw=>JSON.parse(Buffer.from(raw.split('|')[3],'base64url'));
const server=async b=>b.mode?{ok:true,linked:true,playerDbId:a(b.self)[0],notifications:[]}:{ok:true,processed:true};
function env(handler=server,persist={}){const sess={},hooks={start:[],alarm:[]},calls=[];const area=o=>({get:async k=>structuredClone(Object.fromEntries((typeof k==='string'?[k]:Object.keys(k||o)).filter(x=>x in o).map(x=>[x,o[x]]))),set:async x=>Object.assign(o,structuredClone(x))});const chrome={runtime:{id:'test-extension',onStartup:{addListener:f=>hooks.start.push(f)},onInstalled:{addListener:()=>{}}},storage:{local:area(persist),session:area(sess)},alarms:{create:async()=>{},onAlarm:{addListener:f=>hooks.alarm.push(f)}}};const c=vm.createContext({chrome,URL,Date,TextDecoder,atob,AbortController,setTimeout,clearTimeout,console,fetch:async(url,o)=>{const b=JSON.parse(o.body);calls.push(b);const r=await handler(b);return{ok:r.ok!==false,status:r.http||200,json:async()=>r};}});vm.runInContext(source,c);return{persist,sess,calls,hooks,call:(m,s=sender())=>c.HubIdentityV2.handle(m,s),settle:async()=>{for(let i=0;i<200;i++){await new Promise(r=>setTimeout(r,2));if(persist.hubIdentityV2&&!persist.hubIdentityV2.queue.some(x=>x.next<=Date.now()))break;}await new Promise(r=>setTimeout(r,10));}};}
(async()=>{
 await test('reject non-Bloxd sender',async()=>{const e=env();assert.equal((await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw:event()},{...sender(),url:'https://attacker.invalid/'})).ok,false);assert.equal(e.calls.length,0);});
 await test('process signed observation without local old-name cache',async()=>{const e=env();await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw:event()});await e.settle();assert.equal(e.persist.hubIdentityV2.processed,1);});
 await test('twenty concurrent events are retained',async()=>{const e=env();await Promise.all(Array.from({length:20},(_,i)=>e.call({type:'HUB_IDENTITY_V2_ASSERT',raw:event(i)})));await e.settle();assert.equal(e.persist.hubIdentityV2.done.length,20);assert.equal(e.persist.hubIdentityV2.processed,20);});
 await test('duplicate event uploads once',async()=>{const e=env(),raw=event();await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw});await e.settle();await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw});await e.settle();assert.equal(e.calls.length,1);});
 await test('processing false never counts as success',async()=>{const e=env(async()=>({ok:true,processed:false}));await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw:event()});await e.settle();assert.equal(e.persist.hubIdentityV2.processed,0);assert.equal(e.persist.hubIdentityV2.queue.length,1);});
 await test('network error queue survives worker restart',async()=>{const storage={},e=env(async()=>{throw Error('offline');},storage);await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw:event()});await e.settle();storage.hubIdentityV2.queue[0].next=0;const n=env(server,storage);n.hooks.start.forEach(f=>f());await n.settle();assert.equal(storage.hubIdentityV2.processed,1);assert.equal(storage.hubIdentityV2.queue.length,0);});
 await test('signature error is rejected, not processed',async()=>{const e=env(async()=>({ok:false,error:'signature',http:401}));await e.call({type:'HUB_IDENTITY_V2_ASSERT',raw:event()});await e.settle();assert.equal(e.persist.hubIdentityV2.processed,0);assert.equal(e.persist.hubIdentityV2.queue.length,0);});
 const id='hub-id2:AliceDb111111:'+('n'.repeat(43)),notice={id,fromName:'OldAlice',toName:'Alice'};
 await test('server notice survives faster remote bridge',async()=>{const e=env(async()=>({ok:true,linked:true,playerDbId:'AliceDb111111',notifications:[notice]}));const r=await e.call({type:'HUB_IDENTITY_V2_SELF',raw:own()});assert.equal(r.notifications[0].fromName,'OldAlice');assert.ok(!e.persist.hubIdentityV2?.shown.length);});
 await test('frame/document identity is isolated',async()=>{const e=env();await e.call({type:'HUB_IDENTITY_V2_SELF',raw:own('AliceDb111111')},sender(1,0,'a'));await e.call({type:'HUB_IDENTITY_V2_SELF',raw:own('BobDb22222222')},sender(1,1,'b'));assert.equal(e.sess.hubIdentityV2Sessions['1:0:a'].dbId,'AliceDb111111');assert.equal(e.sess.hubIdentityV2Sessions['1:1:b'].dbId,'BobDb22222222');});
 await test('older async self proof cannot replace newer identity',async()=>{const ts=Date.now(),e=env(async b=>{const f=a(b.self);if(f[3]===ts)await new Promise(r=>setTimeout(r,25));return{ok:true,linked:true,playerDbId:f[0],notifications:[]};});await Promise.all([e.call({type:'HUB_IDENTITY_V2_SELF',raw:own('OldDb11111111',ts)}),e.call({type:'HUB_IDENTITY_V2_SELF',raw:own('NewDb22222222',ts+1)})]);assert.equal(e.sess.hubIdentityV2Sessions['1:0:a'].dbId,'NewDb22222222');});
 await test('unoffered notification cannot be acknowledged',async()=>{const e=env();await e.call({type:'HUB_IDENTITY_V2_SELF',raw:own()});assert.equal((await e.call({type:'HUB_IDENTITY_V2_DISPLAYED',notificationId:id})).ok,false);});
 await test('explicit displayed acknowledgement is required',async()=>{const e=env(async b=>b.mode==='ack'?{ok:true,acknowledged:true}:{ok:true,linked:true,playerDbId:'AliceDb111111',notifications:[notice]});await e.call({type:'HUB_IDENTITY_V2_SELF',raw:own()});assert.ok(!e.persist.hubIdentityV2?.shown.length);await e.call({type:'HUB_IDENTITY_V2_DISPLAYED',notificationId:id});assert.ok(e.persist.hubIdentityV2.shown.includes(id));});
 fs.writeFileSync(path.join(root,'results/worker-tests.json'),JSON.stringify({production_requests:0,kind:'Chrome storage/session and HTTP mocks; actual candidate worker',results},null,2)+'\n');console.log(JSON.stringify({passed:results.length,production_requests:0}));
})().catch(e=>{console.error(e);process.exitCode=1;});
